#!/usr/bin/env python3
"""
Generador y exportador de nubes de puntos 3D
Soporta múltiples formatos: PLY, XYZ, PCD, OBJ
"""

import numpy as np
import struct
from pathlib import Path
from typing import List, Tuple, Optional, Dict, Any
from datetime import datetime

from utils.logger import get_logger, PerformanceLogger

logger = get_logger(__name__)

class PointCloudExporter:
    """Exportador de nubes de puntos en múltiples formatos"""
    
    def __init__(self):
        """Inicializar exportador"""
        self.supported_formats = ['ply', 'xyz', 'pcd', 'obj']
        logger.info("Exportador de nubes de puntos inicializado")
    
    def export_point_cloud(self, points: np.ndarray, colors: np.ndarray, 
                          output_file: str, format_type: str = 'ply',
                          normals: Optional[np.ndarray] = None,
                          metadata: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """
        Exportar nube de puntos en el formato especificado
        
        Args:
            points: Array de puntos 3D (N x 3)
            colors: Array de colores RGB (N x 3) en rango [0, 1]
            output_file: Ruta del archivo de salida
            format_type: Formato de exportación ('ply', 'xyz', 'pcd', 'obj')
            normals: Array opcional de normales (N x 3)
            metadata: Metadatos adicionales
            
        Returns:
            Diccionario con resultado de exportación
        """
        
        if format_type.lower() not in self.supported_formats:
            return {
                'success': False,
                'error': f"Formato no soportado: {format_type}"
            }
        
        if len(points) == 0:
            return {
                'success': False,
                'error': "Nube de puntos vacía"
            }
        
        if len(points) != len(colors):
            return {
                'success': False,
                'error': f"Número de puntos ({len(points)}) no coincide con colores ({len(colors)})"
            }
        
        try:
            with PerformanceLogger(f"Exportación {format_type.upper()}", logger):
                
                # Asegurar que el directorio de salida existe
                Path(output_file).parent.mkdir(parents=True, exist_ok=True)
                
                # Exportar según formato
                if format_type.lower() == 'ply':
                    result = self._export_ply(points, colors, output_file, normals, metadata)
                elif format_type.lower() == 'xyz':
                    result = self._export_xyz(points, colors, output_file)
                elif format_type.lower() == 'pcd':
                    result = self._export_pcd(points, colors, output_file, normals, metadata)
                elif format_type.lower() == 'obj':
                    result = self._export_obj(points, colors, output_file, normals)
                
                if result['success']:
                    # Calcular tamaño del archivo
                    file_size = Path(output_file).stat().st_size
                    result['file_size_bytes'] = file_size
                    result['file_size_mb'] = file_size / (1024 * 1024)
                    
                    logger.info(f"Nube exportada: {output_file} ({result['file_size_mb']:.2f} MB)")
                
                return result
                
        except Exception as e:
            logger.error(f"Error exportando nube de puntos: {e}")
            return {
                'success': False,
                'error': str(e)
            }
    
    def _export_ply(self, points: np.ndarray, colors: np.ndarray, 
                   output_file: str, normals: Optional[np.ndarray] = None,
                   metadata: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """Exportar en formato PLY (Polygon File Format)"""
        
        try:
            num_points = len(points)
            
            # Convertir colores a rango [0, 255]
            colors_255 = (colors * 255).astype(np.uint8)
            
            with open(output_file, 'w') as f:
                # Escribir header PLY
                f.write("ply\n")
                f.write("format ascii 1.0\n")
                
                # Metadatos como comentarios
                if metadata:
                    f.write(f"comment Generated by Stereo Photogrammetry CM5\n")
                    f.write(f"comment Timestamp: {datetime.now().isoformat()}\n")
                    
                    for key, value in metadata.items():
                        f.write(f"comment {key}: {value}\n")
                
                f.write(f"element vertex {num_points}\n")
                f.write("property float x\n")
                f.write("property float y\n")
                f.write("property float z\n")
                
                if normals is not None:
                    f.write("property float nx\n")
                    f.write("property float ny\n")
                    f.write("property float nz\n")
                
                f.write("property uchar red\n")
                f.write("property uchar green\n")
                f.write("property uchar blue\n")
                f.write("end_header\n")
                
                # Escribir datos de puntos
                for i in range(num_points):
                    # Coordenadas
                    f.write(f"{points[i, 0]:.6f} {points[i, 1]:.6f} {points[i, 2]:.6f}")
                    
                    # Normales si están disponibles
                    if normals is not None:
                        f.write(f" {normals[i, 0]:.6f} {normals[i, 1]:.6f} {normals[i, 2]:.6f}")
                    
                    # Colores
                    f.write(f" {colors_255[i, 0]} {colors_255[i, 1]} {colors_255[i, 2]}\n")
            
            return {'success': True, 'format': 'PLY', 'points_exported': num_points}
            
        except Exception as e:
            return {'success': False, 'error': f"Error exportando PLY: {e}"}
    
    def _export_xyz(self, points: np.ndarray, colors: np.ndarray, output_file: str) -> Dict[str, Any]:
        """Exportar en formato XYZ simple"""
        
        try:
            num_points = len(points)
            
            # Convertir colores a rango [0, 255]
            colors_255 = (colors * 255).astype(np.uint8)
            
            with open(output_file, 'w') as f:
                # Header simple
                f.write(f"# XYZ Point Cloud - {num_points} points\n")
                f.write(f"# Generated: {datetime.now().isoformat()}\n")
                f.write("# Format: X Y Z R G B\n")
                
                # Escribir puntos
                for i in range(num_points):
                    f.write(f"{points[i, 0]:.6f} {points[i, 1]:.6f} {points[i, 2]:.6f} ")
                    f.write(f"{colors_255[i, 0]} {colors_255[i, 1]} {colors_255[i, 2]}\n")
            
            return {'success': True, 'format': 'XYZ', 'points_exported': num_points}
            
        except Exception as e:
            return {'success': False, 'error': f"Error exportando XYZ: {e}"}
    
    def _export_pcd(self, points: np.ndarray, colors: np.ndarray, output_file: str,
                   normals: Optional[np.ndarray] = None,
                   metadata: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """Exportar en formato PCD (Point Cloud Data)"""
        
        try:
            num_points = len(points)
            
            # Convertir colores a rango [0, 1] para PCD
            colors_float = colors.astype(np.float32)
            
            with open(output_file, 'w') as f:
                # Header PCD
                f.write("# .PCD v0.7 - Point Cloud Data file format\n")
                f.write("VERSION 0.7\n")
                
                # Campos
                if normals is not None:
                    f.write("FIELDS x y z normal_x normal_y normal_z rgb\n")
                    f.write("SIZE 4 4 4 4 4 4 4\n")
                    f.write("TYPE F F F F F F F\n")
                    f.write("COUNT 1 1 1 1 1 1 1\n")
                else:
                    f.write("FIELDS x y z rgb\n")
                    f.write("SIZE 4 4 4 4\n")
                    f.write("TYPE F F F F\n")
                    f.write("COUNT 1 1 1 1\n")
                
                f.write(f"WIDTH {num_points}\n")
                f.write("HEIGHT 1\n")
                f.write("VIEWPOINT 0 0 0 1 0 0 0\n")
                f.write(f"POINTS {num_points}\n")
                f.write("DATA ascii\n")
                
                # Escribir datos
                for i in range(num_points):
                    # Coordenadas
                    f.write(f"{points[i, 0]:.6f} {points[i, 1]:.6f} {points[i, 2]:.6f}")
                    
                    # Normales si están disponibles
                    if normals is not None:
                        f.write(f" {normals[i, 0]:.6f} {normals[i, 1]:.6f} {normals[i, 2]:.6f}")
                    
                    # RGB como float (formato PCD específico)
                    rgb_packed = (int(colors_float[i, 0] * 255) << 16) + \
                               (int(colors_float[i, 1] * 255) << 8) + \
                               int(colors_float[i, 2] * 255)
                    f.write(f" {rgb_packed}\n")
            
            return {'success': True, 'format': 'PCD', 'points_exported': num_points}
            
        except Exception as e:
            return {'success': False, 'error': f"Error exportando PCD: {e}"}
    
    def _export_obj(self, points: np.ndarray, colors: np.ndarray, output_file: str,
                   normals: Optional[np.ndarray] = None) -> Dict[str, Any]:
        """Exportar en formato OBJ (Wavefront OBJ)"""
        
        try:
            num_points = len(points)
            
            # Convertir colores a rango [0, 1]
            colors_float = colors.astype(np.float32)
            
            with open(output_file, 'w') as f:
                # Header OBJ
                f.write("# Wavefront OBJ file\n")
                f.write("# Generated by Stereo Photogrammetry CM5\n")
                f.write(f"# Points: {num_points}\n")
                f.write(f"# Created: {datetime.now().isoformat()}\n\n")
                
                # Escribir vértices
                for i in range(num_points):
                    f.write(f"v {points[i, 0]:.6f} {points[i, 1]:.6f} {points[i, 2]:.6f}")
                    # Colores como parte del vértice (extensión no estándar pero común)
                    f.write(f" {colors_float[i, 0]:.3f} {colors_float[i, 1]:.3f} {colors_float[i, 2]:.3f}\n")
                
                # Escribir normales si están disponibles
                if normals is not None:
                    f.write("\n")
                    for i in range(num_points):
                        f.write(f"vn {normals[i, 0]:.6f} {normals[i, 1]:.6f} {normals[i, 2]:.6f}\n")
                
                # Nota: OBJ es principalmente para mallas, no nubes de puntos
                # Los puntos se almacenan como vértices sin caras
            
            return {'success': True, 'format': 'OBJ', 'points_exported': num_points}
            
        except Exception as e:
            return {'success': False, 'error': f"Error exportando OBJ: {e}"}

class PointCloudProcessor:
    """Procesador para operaciones avanzadas en nubes de puntos"""
    
    def __init__(self):
        """Inicializar procesador"""
        logger.info("Procesador de nubes de puntos inicializado")
    
    def compute_normals(self, points: np.ndarray, k_neighbors: int = 20) -> np.ndarray:
        """
        Calcular normales para cada punto usando PCA local
        
        Args:
            points: Array de puntos (N x 3)
            k_neighbors: Número de vecinos para cálculo de normal
            
        Returns:
            Array de normales (N x 3)
        """
        
        try:
            from sklearn.neighbors import NearestNeighbors
            
            with PerformanceLogger("Cálculo de normales", logger):
                num_points = len(points)
                normals = np.zeros_like(points)
                
                # Crear índice de vecinos más cercanos
                nbrs = NearestNeighbors(n_neighbors=min(k_neighbors, num_points), algorithm='auto')
                nbrs.fit(points)
                
                # Calcular normal para cada punto
                for i in range(num_points):
                    # Encontrar k vecinos más cercanos
                    distances, indices = nbrs.kneighbors([points[i]])
                    neighbor_points = points[indices[0]]
                    
                    # Calcular centroide local
                    centroid = np.mean(neighbor_points, axis=0)
                    
                    # Centrar puntos
                    centered_points = neighbor_points - centroid
                    
                    # PCA para encontrar dirección normal
                    covariance_matrix = np.cov(centered_points.T)
                    eigenvalues, eigenvectors = np.linalg.eigh(covariance_matrix)
                    
                    # La normal es el eigenvector con menor eigenvalue
                    normal_vector = eigenvectors[:, np.argmin(eigenvalues)]
                    
                    # Orientar normal hacia el origen (asumiendo vista desde arriba)
                    if normal_vector[2] < 0:
                        normal_vector = -normal_vector
                    
                    normals[i] = normal_vector
                
                logger.info(f"Normales calculadas para {num_points} puntos")
                return normals
                
        except ImportError:
            logger.warning("sklearn no disponible, usando cálculo simplificado de normales")
            return self._compute_normals_simple(points)
        except Exception as e:
            logger.error(f"Error calculando normales: {e}")
            return np.zeros_like(points)
    
    def _compute_normals_simple(self, points: np.ndarray, grid_size: int = 10) -> np.ndarray:
        """Cálculo simplificado de normales usando vecindad en grilla"""
        
        try:
            num_points = len(points)
            normals = np.zeros_like(points)
            
            # Crear grilla 3D simple para encontrar vecinos
            for i in range(num_points):
                current_point = points[i]
                
                # Encontrar puntos cercanos (método simple)
                distances = np.linalg.norm(points - current_point, axis=1)
                close_indices = np.where(distances < np.percentile(distances, 5))[0]  # 5% más cercanos
                
                if len(close_indices) >= 3:
                    neighbor_points = points[close_indices]
                    
                    # Calcular normal usando productos cruzados
                    if len(neighbor_points) >= 3:
                        # Usar los 3 puntos más cercanos para calcular normal
                        v1 = neighbor_points[1] - neighbor_points[0]
                        v2 = neighbor_points[2] - neighbor_points[0]
                        
                        normal = np.cross(v1, v2)
                        if np.linalg.norm(normal) > 1e-8:
                            normal = normal / np.linalg.norm(normal)
                        else:
                            normal = np.array([0, 0, 1])  # Default hacia arriba
                        
                        normals[i] = normal
                else:
                    # Default normal hacia arriba
                    normals[i] = np.array([0, 0, 1])
            
            return normals
            
        except Exception as e:
            logger.error(f"Error en cálculo simple de normales: {e}")
            # Retornar normales por defecto hacia arriba
            return np.tile(np.array([0, 0, 1]), (len(points), 1))
    
    def filter_outliers(self, points: np.ndarray, colors: np.ndarray,
                       method: str = 'statistical', **kwargs) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
        """
        Filtrar outliers de la nube de puntos
        
        Args:
            points: Array de puntos (N x 3)
            colors: Array de colores (N x 3)
            method: Método de filtrado ('statistical', 'radius')
            **kwargs: Parámetros específicos del método
            
        Returns:
            Tupla con puntos filtrados, colores filtrados y máscara de puntos válidos
        """
        
        try:
            if method == 'statistical':
                return self._filter_statistical_outliers(points, colors, **kwargs)
            elif method == 'radius':
                return self._filter_radius_outliers(points, colors, **kwargs)
            else:
                logger.warning(f"Método de filtrado desconocido: {method}")
                return points, colors, np.ones(len(points), dtype=bool)
                
        except Exception as e:
            logger.error(f"Error filtrando outliers: {e}")
            return points, colors, np.ones(len(points), dtype=bool)
    
    def _filter_statistical_outliers(self, points: np.ndarray, colors: np.ndarray,
                                   nb_neighbors: int = 20, std_ratio: float = 2.0) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
        """Filtrar outliers estadísticos"""
        
        try:
            from sklearn.neighbors import NearestNeighbors
            
            with PerformanceLogger("Filtrado estadístico de outliers", logger):
                # Calcular distancias promedio a vecinos
                nbrs = NearestNeighbors(n_neighbors=min(nb_neighbors, len(points)), algorithm='auto')
                nbrs.fit(points)
                
                distances, _ = nbrs.kneighbors(points)
                mean_distances = np.mean(distances[:, 1:], axis=1)  # Excluir distancia a sí mismo
                
                # Calcular estadísticas
                global_mean = np.mean(mean_distances)
                global_std = np.std(mean_distances)
                
                # Crear máscara de puntos válidos
                threshold = global_mean + std_ratio * global_std
                valid_mask = mean_distances <= threshold
                
                filtered_points = points[valid_mask]
                filtered_colors = colors[valid_mask]
                
                logger.info(f"Filtrado estadístico: {len(filtered_points)}/{len(points)} puntos conservados")
                
                return filtered_points, filtered_colors, valid_mask
                
        except ImportError:
            logger.warning("sklearn no disponible para filtrado estadístico")
            return points, colors, np.ones(len(points), dtype=bool)
    
    def _filter_radius_outliers(self, points: np.ndarray, colors: np.ndarray,
                               radius: float = 0.05, min_neighbors: int = 5) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
        """Filtrar outliers por densidad en radio"""
        
        try:
            from sklearn.neighbors import NearestNeighbors
            
            with PerformanceLogger("Filtrado por radio", logger):
                # Contar vecinos dentro del radio
                nbrs = NearestNeighbors(radius=radius, algorithm='auto')
                nbrs.fit(points)
                
                neighbor_counts = []
                for point in points:
                    distances, indices = nbrs.radius_neighbors([point])
                    neighbor_counts.append(len(indices[0]) - 1)  # Excluir el punto mismo
                
                neighbor_counts = np.array(neighbor_counts)
                
                # Crear máscara de puntos con suficientes vecinos
                valid_mask = neighbor_counts >= min_neighbors
                
                filtered_points = points[valid_mask]
                filtered_colors = colors[valid_mask]
                
                logger.info(f"Filtrado por radio: {len(filtered_points)}/{len(points)} puntos conservados")
                
                return filtered_points, filtered_colors, valid_mask
                
        except ImportError:
            logger.warning("sklearn no disponible para filtrado por radio")
            return points, colors, np.ones(len(points), dtype=bool)
    
    def downsample_voxel_grid(self, points: np.ndarray, colors: np.ndarray,
                             voxel_size: float = 0.01) -> Tuple[np.ndarray, np.ndarray]:
        """
        Reducir densidad usando grilla de vóxeles
        
        Args:
            points: Array de puntos (N x 3)
            colors: Array de colores (N x 3)
            voxel_size: Tamaño del vóxel en metros
            
        Returns:
            Tupla con puntos y colores decimados
        """
        
        try:
            with PerformanceLogger("Decimado con grilla de vóxeles", logger):
                # Calcular índices de vóxeles
                voxel_indices = np.floor(points / voxel_size).astype(int)
                
                # Crear diccionario para agrupar puntos por vóxel
                voxel_dict = {}
                for i, voxel_idx in enumerate(voxel_indices):
                    key = tuple(voxel_idx)
                    if key not in voxel_dict:
                        voxel_dict[key] = []
                    voxel_dict[key].append(i)
                
                # Calcular punto representativo para cada vóxel
                downsampled_points = []
                downsampled_colors = []
                
                for voxel_key, point_indices in voxel_dict.items():
                    if len(point_indices) > 0:
                        # Promedio de puntos y colores en el vóxel
                        voxel_points = points[point_indices]
                        voxel_colors = colors[point_indices]
                        
                        avg_point = np.mean(voxel_points, axis=0)
                        avg_color = np.mean(voxel_colors, axis=0)
                        
                        downsampled_points.append(avg_point)
                        downsampled_colors.append(avg_color)
                
                downsampled_points = np.array(downsampled_points)
                downsampled_colors = np.array(downsampled_colors)
                
                logger.info(f"Decimado: {len(downsampled_points)}/{len(points)} puntos ({len(downsampled_points)/len(points):.1%})")
                
                return downsampled_points, downsampled_colors
                
        except Exception as e:
            logger.error(f"Error en decimado de vóxeles: {e}")
            return points, colors

if __name__ == "__main__":
    # Test del generador de nubes de puntos
    try:
        print("Probando generador de nubes de puntos...")
        
        # Crear datos de prueba
        n_points = 1000
        points = np.random.rand(n_points, 3) * 2 - 1  # Puntos en [-1, 1]
        colors = np.random.rand(n_points, 3)  # Colores aleatorios
        
        # Test exportador
        exporter = PointCloudExporter()
        
        # Test exportación PLY
        result = exporter.export_point_cloud(points, colors, "test_output.ply", "ply")
        print(f"✓ Exportación PLY: {'Exitosa' if result['success'] else 'Falló'}")
        if result['success']:
            print(f"  Puntos exportados: {result['points_exported']}")
            print(f"  Tamaño archivo: {result.get('file_size_mb', 0):.2f} MB")
        
        # Test procesador
        processor = PointCloudProcessor()
        
        # Test cálculo de normales
        normals = processor.compute_normals(points[:100])  # Solo 100 puntos para test
        print(f"✓ Cálculo de normales: {normals.shape}")
        
        # Test filtrado de outliers
        filtered_points, filtered_colors, mask = processor.filter_outliers(points, colors, method='statistical')
        print(f"✓ Filtrado de outliers: {len(filtered_points)}/{len(points)} puntos conservados")
        
        # Test decimado
        decimated_points, decimated_colors = processor.downsample_voxel_grid(points, colors, voxel_size=0.1)
        print(f"✓ Decimado: {len(decimated_points)}/{len(points)} puntos conservados")
        
        # Limpiar archivo de test
        import os
        if os.path.exists("test_output.ply"):
            os.unlink("test_output.ply")
        
        print("✓ Todas las pruebas pasaron")
        
    except Exception as e:
        print(f"✗ Error en pruebas: {e}")
        import sys
        sys.exit(1)